# Adapted from dfm/george

language: python

matrix:
  include:
    # All the versions of Python.
    - python: 2.7
    - python: 3.4
    - python: 3.6

cache: pip

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy matplotlib nose pip
  - pip install coveralls
  - python setup.py install

script: 
  - nosetests -w tests
  - coverage run --source=pysyzygy setup.py test

after_success:
  - coveralls